[features]
seeds = false
skip-lint = false

[programs.devnet]
token = "CwjJL7vfk73PkNtJLaFxN75upZYKnzXGP1CCwH8ayxWu"

[registry]
url = "https://api.devnet.solana.com"   # Change as per your requirement

[provider]
cluster = "devnet" 
wallet = "/home/ubuntu/.config/solana/id.json"   # Put your wallet path
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
